export const hospitalsData = [
  {
    id: 'shanghai-east',
    name: 'Shanghai East Hospital',
    nameCn: '上海市东方医院',
    city: 'Shanghai',
    rating: 4.8,
    reviews: 127,
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b9af923?w=800&q=80',
    description: 'One of Shanghai\'s top hospitals with a dedicated International Medical Center serving expats and medical tourists since 2005.',
    longDescription: `Shanghai East Hospital is a comprehensive tertiary hospital directly under the Shanghai Municipal Health Commission. Established in 1920, it has grown to become one of the leading medical institutions in China.

The hospital features a state-of-the-art International Medical Center that provides comprehensive healthcare services to foreign patients. With over 2,000 beds and more than 3,000 medical professionals, the hospital offers a full range of medical services from routine checkups to complex surgeries.`,
    address: '150 Jimo Road, Pudong New Area, Shanghai',
    phone: '+86 21 3880 9999',
    email: 'imc@shdfty.com',
    website: 'https://www.shdfty.com',
    certifications: ['JCI', 'Grade 3A', 'ISO 9001'],
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurosurgery', 'Traditional Chinese Medicine'],
    languages: ['English', 'Japanese', 'Korean', 'Arabic'],
    facilities: [
      '24/7 Emergency Department',
      'International Patient Center',
      'VIP Wards',
      'Pharmacy',
      'Medical Imaging Center',
      'Laboratory',
    ],
    doctors: [
      { name: 'Dr. Zhang Wei', title: 'Chief Cardiologist', specialty: 'Cardiology', experience: 25 },
      { name: 'Dr. Li Ming', title: 'Senior Oncologist', specialty: 'Oncology', experience: 20 },
      { name: 'Dr. Wang Fang', title: 'Orthopedic Surgeon', specialty: 'Orthopedics', experience: 18 },
    ],
    priceExamples: [
      { service: 'Comprehensive Health Checkup', price: 2800, priceUsd: 400 },
      { service: 'Cardiac Consultation', price: 500, priceUsd: 70 },
      { service: 'MRI Scan', price: 1200, priceUsd: 170 },
      { service: 'Dental Implant', price: 8000, priceUsd: 1150 },
    ],
  },
  {
    id: 'peking-union',
    name: 'Peking Union Medical College Hospital',
    nameCn: '北京协和医院',
    city: 'Beijing',
    rating: 4.9,
    reviews: 203,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80',
    description: 'Consistently ranked #1 in China, with over 90 years of history and world-class medical expertise.',
    longDescription: `Peking Union Medical College Hospital (PUMCH) is one of the most prestigious hospitals in China. Founded in 1921, it has consistently been ranked as the top hospital in China for over a decade.

The hospital is renowned for its exceptional medical care, research, and education. It serves as a national center for complex and rare diseases, attracting patients from all over China and abroad.`,
    address: '1 Shuaifuyuan, Dongcheng District, Beijing',
    phone: '+86 10 6915 6114',
    email: 'international@pumch.cn',
    website: 'https://www.pumch.cn',
    certifications: ['Grade 3A', 'National Key Hospital'],
    specialties: ['Internal Medicine', 'Surgery', 'Dermatology', 'Endocrinology', 'Rheumatology'],
    languages: ['English', 'Japanese'],
    facilities: [
      'International Medical Center',
      'Specialty Clinics',
      'Advanced Diagnostic Center',
      'Research Facilities',
      'Teaching Hospital',
    ],
    doctors: [
      { name: 'Dr. Chen Hua', title: 'Professor of Internal Medicine', specialty: 'Internal Medicine', experience: 30 },
      { name: 'Dr. Liu Ying', title: 'Chief Dermatologist', specialty: 'Dermatology', experience: 22 },
      { name: 'Dr. Zhao Gang', title: 'Endocrine Specialist', specialty: 'Endocrinology', experience: 19 },
    ],
    priceExamples: [
      { service: 'General Consultation', price: 300, priceUsd: 43 },
      { service: 'Specialist Consultation', price: 800, priceUsd: 115 },
      { service: 'CT Scan', price: 1500, priceUsd: 215 },
      { service: 'Comprehensive Physical', price: 5000, priceUsd: 715 },
    ],
  },
  {
    id: 'shanghai-9th',
    name: '9th People\'s Hospital Shanghai',
    nameCn: '上海第九人民医院',
    city: 'Shanghai',
    rating: 4.7,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&q=80',
    description: 'Renowned for dental and cosmetic surgery, offering significant cost savings compared to Western countries.',
    longDescription: `The 9th People\'s Hospital of Shanghai is world-famous for its dental and plastic surgery departments. It is affiliated with Shanghai Jiao Tong University School of Medicine.

The hospital attracts thousands of medical tourists annually seeking high-quality dental implants, cosmetic procedures, and reconstructive surgery at a fraction of Western prices.`,
    address: '639 Zhizaoju Road, Huangpu District, Shanghai',
    phone: '+86 21 2327 1699',
    email: 'international@9thhospital.com',
    website: 'https://www.9thhospital.com',
    certifications: ['Grade 3A', 'Key Dental Center'],
    specialties: ['Dental', 'Plastic Surgery', 'Ophthalmology', 'Orthopedics'],
    languages: ['English', 'Korean'],
    facilities: [
      'Dental Implant Center',
      'Cosmetic Surgery Center',
      'Laser Treatment Center',
      '3D Printing Lab',
    ],
    doctors: [
      { name: 'Dr. Wu Jing', title: 'Chief Dental Surgeon', specialty: 'Dental', experience: 28 },
      { name: 'Dr. Sun Li', title: 'Plastic Surgeon', specialty: 'Plastic Surgery', experience: 15 },
      { name: 'Dr. Zhou Min', title: 'Ophthalmologist', specialty: 'Ophthalmology', experience: 20 },
    ],
    priceExamples: [
      { service: 'Dental Implant', price: 6000, priceUsd: 860 },
      { service: 'Teeth Whitening', price: 1500, priceUsd: 215 },
      { service: 'LASIK Surgery', price: 12000, priceUsd: 1720 },
      { service: 'Botox Treatment', price: 2000, priceUsd: 285 },
    ],
  },
  {
    id: 'guangdong-provincial',
    name: 'Guangdong Provincial People\'s Hospital',
    nameCn: '广东省人民医院',
    city: 'Guangzhou',
    rating: 4.6,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80',
    description: 'Leading hospital in South China with comprehensive international patient services.',
    longDescription: `Guangdong Provincial People's Hospital is one of the largest and most comprehensive hospitals in South China. Established in 1946, it has a long history of providing excellent medical care.

The hospital is particularly strong in cardiology and cardiovascular surgery, with a dedicated heart center that serves patients from across Southeast Asia.`,
    address: '96 Zhongshan Er Road, Yuexiu District, Guangzhou',
    phone: '+86 20 8382 7812',
    email: 'international@gdphospital.org',
    website: 'https://www.gdphospital.org',
    certifications: ['JCI', 'Grade 3A'],
    specialties: ['Cardiology', 'Neurology', 'Oncology', 'Geriatrics'],
    languages: ['English', 'Cantonese'],
    facilities: [
      'Heart Center',
      'Stroke Center',
      'Cancer Center',
      'International Ward',
    ],
    doctors: [
      { name: 'Dr. Huang Wei', title: 'Cardiac Surgeon', specialty: 'Cardiology', experience: 26 },
      { name: 'Dr. Lin Tao', title: 'Neurologist', specialty: 'Neurology', experience: 21 },
    ],
    priceExamples: [
      { service: 'Heart Checkup', price: 3500, priceUsd: 500 },
      { service: 'ECG', price: 100, priceUsd: 14 },
      { service: 'Echocardiogram', price: 400, priceUsd: 57 },
    ],
  },
  {
    id: 'west-china',
    name: 'West China Hospital',
    nameCn: '四川大学华西医院',
    city: 'Chengdu',
    rating: 4.8,
    reviews: 134,
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b9af923?w=800&q=80',
    description: 'The largest single-site hospital in the world, combining Western medicine with Traditional Chinese Medicine.',
    longDescription: `West China Hospital of Sichuan University is the largest single-site hospital in the world. It is consistently ranked among the top hospitals in China.

The hospital is famous for integrating modern Western medicine with Traditional Chinese Medicine (TCM), offering patients the best of both worlds.`,
    address: '37 Guoxue Road, Wuhou District, Chengdu',
    phone: '+86 28 8542 2114',
    email: 'international@wchscu.cn',
    website: 'https://www.wchscu.cn',
    certifications: ['Grade 3A', 'TCM Integration Center'],
    specialties: ['Neurosurgery', 'Cardiology', 'Traditional Chinese Medicine', 'Gastroenterology'],
    languages: ['English'],
    facilities: [
      'TCM Center',
      'Acupuncture Clinic',
      'Herbal Medicine Pharmacy',
      'Rehabilitation Center',
    ],
    doctors: [
      { name: 'Dr. Yang Bo', title: 'Neurosurgeon', specialty: 'Neurosurgery', experience: 24 },
      { name: 'Dr. Master Li', title: 'TCM Practitioner', specialty: 'Traditional Chinese Medicine', experience: 35 },
    ],
    priceExamples: [
      { service: 'Acupuncture Session', price: 200, priceUsd: 29 },
      { service: 'TCM Consultation', price: 150, priceUsd: 21 },
      { service: 'Herbal Medicine (1 week)', price: 500, priceUsd: 71 },
    ],
  },
  {
    id: 'sir-run-run-shaw',
    name: 'Sir Run Run Shaw Hospital',
    nameCn: '浙江大学医学院附属邵逸夫医院',
    city: 'Hangzhou',
    rating: 4.7,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80',
    description: 'Joint venture hospital with US management, offering international standards at local prices.',
    longDescription: `Sir Run Run Shaw Hospital is a unique joint venture between China and the United States. It was established with support from the Sir Run Run Shaw Foundation and features American-style hospital management.

The hospital is known for its patient-centered approach and modern facilities, making it a popular choice for expats and medical tourists in the Yangtze River Delta region.`,
    address: '3 Qingchun East Road, Jianggan District, Hangzhou',
    phone: '+86 571 8600 6001',
    email: 'international@srrsh.com',
    website: 'https://www.srrsh.com',
    certifications: ['JCI', 'Grade 3A'],
    specialties: ['Oncology', 'Gastroenterology', 'Minimally Invasive Surgery', 'Women\'s Health'],
    languages: ['English', 'Japanese'],
    facilities: [
      'Cancer Center',
      'Minimally Invasive Surgery Center',
      'Women\'s Health Center',
      'International Patient Services',
    ],
    doctors: [
      { name: 'Dr. Xu Mei', title: 'Oncologist', specialty: 'Oncology', experience: 23 },
      { name: 'Dr. Chen Feng', title: 'Surgeon', specialty: 'Minimally Invasive Surgery', experience: 17 },
    ],
    priceExamples: [
      { service: 'Cancer Screening', price: 3000, priceUsd: 430 },
      { service: 'Laparoscopic Surgery', price: 15000, priceUsd: 2150 },
      { service: 'Women\'s Health Check', price: 2000, priceUsd: 285 },
    ],
  },
]

export const specialtiesList = [
  'Cardiology', 'Oncology', 'Orthopedics', 'Internal Medicine', 
  'Surgery', 'Dermatology', 'Dental', 'Plastic Surgery',
  'Ophthalmology', 'Neurology', 'Gastroenterology', 'Neurosurgery',
  'Traditional Chinese Medicine', 'Endocrinology', 'Rheumatology',
  'Geriatrics', 'Women\'s Health', 'Minimally Invasive Surgery'
]

export const citiesList = ['All Cities', 'Shanghai', 'Beijing', 'Guangzhou', 'Chengdu', 'Hangzhou']
